"""Generate docs/adr/index.md from ADR frontmatter."""
import argparse

from madr_tools.config import get_adr_index_file
from madr_tools.log import info, success
from madr_tools.parser import load_all

STATUS_ORDER = ("accepted", "proposed", "deprecated", "superseded", "rejected")


def run(args: argparse.Namespace | None = None) -> int:
    prefix = "index"

    docs = load_all(strict=False)
    info(prefix, f"loaded {len(docs)} ADRs")

    docs.sort(key=lambda d: (STATUS_ORDER.index(d.meta.status) if d.meta.status in STATUS_ORDER else 99, d.number))

    lines = [
        "# ADRs",
        "",
        "> Architecture Decision Records — auto-generated by `adr index`.",
        "",
        "| ADR | Title | Status | Date | Supersedes |",
        "|-----|-------|--------|------|------------|",
    ]
    for doc in docs:
        supersedes = doc.meta.supersedes or ""
        lines.append(f"| {doc.adr_id} | {doc.title} | {doc.meta.status} | {doc.meta.date} | {supersedes} |")
    lines.append("")

    index_file = get_adr_index_file()
    index_file.write_text("\n".join(lines))
    info(prefix, f"wrote {index_file} — {len(docs)} ADRs")

    success(f"index regenerated with {len(docs)} ADRs")
    return 0
