"""Generate docs/adr/index.md from ADR frontmatter."""
import argparse
from madr_tools.config import get_adr_index_file
from madr_tools.parser import load_all

STATUS_ORDER = ("accepted", "proposed", "deprecated", "superseded", "rejected")

def run(args: argparse.Namespace | None = None) -> int:
    docs = load_all(strict=False)
    docs.sort(key=lambda d: (STATUS_ORDER.index(d.meta.status) if d.meta.status in STATUS_ORDER else 99, d.number))
    lines = [
        "# ADRs", "",
        "> Architecture Decision Records — auto-generated by `adr index`.", "",
        "| ADR | Title | Status | Date | Supersedes |",
        "|-----|-------|--------|------|------------|",
    ]
    for doc in docs:
        supersedes = doc.meta.supersedes or ""
        lines.append(f"| {doc.adr_id} | {doc.title} | {doc.meta.status} | {doc.meta.date} | {supersedes} |")
    lines.append("")
    get_adr_index_file().write_text("\n".join(lines))
    return 0
