"""Generate index.md files from document frontmatter — one per doc type."""

import argparse

from decree.log import info, success

GRAPH_MARKER = "<!-- GENERATED:decree-graph — do not edit below this line -->"


def run(args: argparse.Namespace | None = None) -> int:
    from decree.config import get_project_root, load_doc_types
    from decree.parser import load_all

    prefix = "index"
    doc_types = load_doc_types()

    for dt in doc_types:
        type_dir = get_project_root() / dt.dir
        type_dir.mkdir(parents=True, exist_ok=True)

        docs = load_all(doc_type=dt)
        info(prefix, f"loaded {len(docs)} {dt.name.upper()} documents")

        # Use a display order that puts "active/accepted" statuses first.
        # For ADR type (and any type), derive display order by putting statuses
        # that have outgoing transitions (active) before terminal ones, with
        # accepted/approved/implemented active statuses prioritized.
        # Fall back to the statuses tuple order if not derivable.
        _preferred = [
            "accepted",
            "approved",
            "implemented",
            "proposed",
            "draft",
            "review",
            "deprecated",
            "superseded",
            "rejected",
            "archived",
        ]
        STATUS_ORDER = sorted(dt.statuses, key=lambda s: _preferred.index(s) if s in _preferred else 99)
        docs.sort(
            key=lambda d: (
                STATUS_ORDER.index(d.meta.status) if d.meta.status in STATUS_ORDER else 99,
                d.meta.date,
                d.doc_id,
            )
        )

        type_upper = dt.name.upper()

        # Include Supersedes column only when the type uses supersede semantics
        has_supersedes = any(target == "superseded" for target in dt.actions.values())

        if has_supersedes:
            lines = [
                f"# {type_upper}s",
                "",
                f"> {type_upper} documents — auto-generated by `decree index regenerate`.",
                "",
                f"| {type_upper} | Title | Status | Date | Supersedes |",
                "|-----|-------|--------|------|------------|",
            ]
            for doc in docs:
                supersedes = doc.meta.supersedes or ""
                lines.append(f"| {doc.doc_id} | {doc.title} | {doc.meta.status} | {doc.meta.date} | {supersedes} |")
        else:
            lines = [
                f"# {type_upper}s",
                "",
                f"> {type_upper} documents — auto-generated by `decree index regenerate`.",
                "",
                f"| {type_upper} | Title | Status | Date |",
                f"|{'-----|' * 4}",
            ]
            for doc in docs:
                lines.append(f"| {doc.doc_id} | {doc.title} | {doc.meta.status} | {doc.meta.date} |")

        lines.append("")
        lines.append(GRAPH_MARKER)
        lines.append("")

        index_file = type_dir / "index.md"
        index_file.write_text("\n".join(lines))
        info(prefix, f"wrote {index_file} — {len(docs)} documents")

    success(f"index regenerated for {len(doc_types)} type(s)")
    return 0
